# Generated by Django 3.2.5 on 2021-07-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='id', serialize=False, to='auth.user')),
                ('Firstname', models.CharField(max_length=15, null=True)),
                ('Lastname', models.CharField(max_length=15, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Email', models.CharField(max_length=25, null=True)),
                ('Address1', models.CharField(max_length=30, null=True)),
                ('Address2', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=15, null=True)),
                ('State', models.CharField(max_length=15, null=True)),
                ('Zip', models.CharField(max_length=10, null=True)),
                ('Country', models.CharField(max_length=15, null=True)),
                ('CMA', models.CharField(max_length=15, null=True)),
                ('Urbanization', models.CharField(max_length=50, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('DonationsType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donation.donationtype')),
            ],
        ),
    ]
