
# Generated by Django 3.2.5 on 2021-07-19 18:23

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),

                ('CMA', models.CharField(max_length=15, null=True)),
                ('Urbanization', models.CharField(max_length=50, null=True)),
                ('Title', models.CharField(choices=[('GeneralDonationFund', 'General Donation Fund'), ('RunForTheSon2017', 'Run for the Son 2017'), ('MissionTripSponsorship', 'Mission Trip Sponsorship'), ('MemorialGift', 'Memorial Gift')], default='', max_length=22)),
                ('DonationType', models.CharField(choices=[('MW', 'Mighty Warriors'), ('RS', 'Run For The Sun'), ('MT', 'Mission Trip'), ('MG', 'Memorial Gift')], default='', max_length=2)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='user_id', serialize=False, to='auth.user')),
                ('Firstname', models.CharField(max_length=15, null=True)),
                ('Lastname', models.CharField(max_length=15, null=True)),


                ('Phone', models.CharField(max_length=15, null=True)),
                ('Email', models.CharField(max_length=25, null=True)),
                ('Address1', models.CharField(max_length=30, null=True)),
                ('Address2', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=15, null=True)),
                ('State', models.CharField(max_length=15, null=True)),
                ('Zip', models.CharField(max_length=10, null=True)),

                ('Donations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donation.donation')),
            ],
        ),
    ]
