# Generated by Django 3.2.5 on 2021-07-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='user',
            new_name='user_id',
        ),
    ]
