# Generated by Django 3.2.5 on 2021-07-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='Address1',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='City',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='State',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Zip',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='user_id', serialize=False, to='auth.user')),
                ('Firstname', models.CharField(max_length=15, null=True)),
                ('Lastname', models.CharField(max_length=15, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Email', models.CharField(max_length=25, null=True)),
                ('Address1', models.CharField(max_length=30, null=True)),
                ('Address2', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=15, null=True)),
                ('State', models.CharField(max_length=15, null=True)),
                ('Zip', models.CharField(max_length=10, null=True)),
                ('Country', models.CharField(max_length=15, null=True)),
                ('Donations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
            ],
        ),
    ]
