# Generated by Django 3.2.5 on 2021-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_user_donation_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
