# Generated by Django 3.2.5 on 2021-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20210719_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='MemorialGift',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='MissionTripSponsorship',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='RunForTheSon2017',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
