# Generated by Django 3.2.5 on 2021-07-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donationtype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='DonationsType',
        ),
        migrations.AddField(
            model_name='donation',
            name='DonationType',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
